CC = gcc
CFLAGS = -Wall
all: vd1 vd2 alarm
vd1: vd1.c
	$(CC) $(CFLAGS) -o vd1 vd1.c
vd2: vd2.c
	$(CC) $(CFLAGS) -o vd2 vd2.c
alarm: alarm.c
	$(CC) $(CFLAGS) -o alarm alarm.c
clean:
	rm -f vd1 vd2 alarm
