all:
	$(MAKE) -C bt2
	$(MAKE) -C bt3
	$(MAKE) -C bt4
	$(MAKE) -C bt5
	$(MAKE) -C bt6

clean:
	$(MAKE) -C bt2 clean
	$(MAKE) -C bt3 clean
	$(MAKE) -C bt4 clean
	$(MAKE) -C bt5 clean
	$(MAKE) -C bt6 clean
